// Generates a large project to test the performance of the user interface.
// Usage: node scripts/seed-big.mjs [dataDir=.planner-data] [tasks=5000]
// Then: pnpm dev (uses .planner-data) or PLANNER_DATA_DIR=<folder> with the built app.
import { randomUUID } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const dataDir = resolve(process.argv[2] ?? '.planner-data')
const n = Number(process.argv[3] ?? 5000)
let seed = 7
const rnd = (mod) => {
  seed = (seed * 1103515245 + 12345) % 2147483648
  return seed % mod
}
const now = new Date().toISOString()
const WORDS = ['Design', 'Implement', 'Review', 'Test', 'Document', 'Integrate', 'Migrate', 'Optimize', 'Configure', 'Validate']
const THINGS = ['API', 'screen', 'report', 'model', 'service', 'pipeline', 'component', 'module', 'flow', 'schema']

const members = ['Emma Wilson', 'James Carter', 'Olivia Brown', 'Liam Johnson', 'Sophia Lee'].map((name, i) => ({
  id: randomUUID(),
  name,
  role: ['Frontend', 'Backend', 'Design', 'QA', 'DevOps'][i],
  initials: name.split(' ').map((w) => w[0]).join(''),
  color: ['#6366f1', '#0ea5e9', '#10b981', '#f59e0b', '#ec4899'][i],
  rateCents: [5000, 5500, 4000, 3800, 6000][i],
  hoursPerDay: [7, 8, 6, 8, 5][i]
}))

const ids = Array.from({ length: n }, () => randomUUID())
const depth = new Map()
const children = {}
const parents = {}
const roots = []
ids.forEach((id, i) => {
  if (i < 15) {
    roots.push(id)
    depth.set(id, 0)
    return
  }
  let p = ids[rnd(i)]
  while (depth.get(p) >= 9) p = ids[rnd(i)]
  depth.set(id, depth.get(p) + 1)
  parents[id] = [p]
  ;(children[p] ??= []).push(id)
})
// 10% shared subtasks (a second edge to an earlier task: no cycles).
for (let k = 0; k < n / 10; k++) {
  const i = 15 + rnd(n - 15)
  const child = ids[i]
  const p = ids[rnd(i)]
  if (p === child || parents[child].includes(p)) continue
  parents[child].push(p)
  ;(children[p] ??= []).push(child)
}

const statuses = ['todo', 'todo', 'in_progress', 'review', 'done']
const tasks = ids.map((id) => {
  const leaf = !children[id]
  return {
    id,
    title: `${WORDS[rnd(WORDS.length)]} ${THINGS[rnd(THINGS.length)]} ${rnd(900) + 100}`,
    description: '',
    status: statuses[rnd(statuses.length)],
    priority: ['low', 'medium', 'medium', 'high', 'critical'][rnd(5)],
    storyPoints: leaf ? [1, 2, 3, 5, 8][rnd(5)] : null,
    estimateMinutes: leaf ? (1 + rnd(16)) * 30 : null,
    assigneeId: leaf ? members[rnd(members.length)].id : null,
    rateCents: null,
    tags: [],
    createdAt: now,
    updatedAt: now
  }
})

const projectId = randomUUID()
const doc = {
  format: 'planner.project',
  schemaVersion: 1,
  meta: {
    id: projectId,
    name: `Large project (${n} tasks)`,
    client: 'Performance test',
    description: 'Generated by scripts/seed-big.mjs',
    color: '#8b5cf6',
    currency: 'EUR',
    defaultRateCents: 4500,
    defaultHoursPerDay: 8,
    startDate: now.slice(0, 10),
    workingWeekdays: [1, 2, 3, 4, 5],
    contingencyBps: 1000,
    taxBps: 2100,
    taxLabel: '',
    quote: { number: 'P-BIG', date: null, validityDays: 30, terms: '' },
    archived: false,
    createdAt: now,
    updatedAt: now
  },
  members,
  tasks,
  structure: { roots, children, parents }
}

const dir = join(dataDir, 'projects')
mkdirSync(dir, { recursive: true })
writeFileSync(join(dir, `${projectId}.json`), JSON.stringify(doc))
const shared = Object.values(parents).filter((p) => p.length > 1).length
console.log(`Project with ${n} tasks (${shared} shared) created in ${dir}`)
